### ISSUE TITLE
[Use Case] Setting my own data to open access

### ISSUE THREAD

**Issue by joerg-halo** [halo-db/storymap#39]
As Data Provider I want to set the data I uploaded to open access already before all campaign data become freely accessible. Thus, I want to encourage the data I retrieved.

**Comment by bjoernbroetz** [comment]
There should be a set of selectable standard open licenses provided.

**Comment by joerg-halo** [comment]
This is a special case of #19, when the data are not only released to a certain group but to everybody. As #19 covers this already I close this use case.
